### ISSUE TITLE
OSError: [E050] Can't find model 

### ISSUE THREAD

**Issue by TheGreatSimo** [sai-prasanna/lmproof#10]
I was trying to write a small spell checker
I installed lmproof by:
`pip install lmproof`
I tried to run the small program but I faced this error 

```/#####/####/.local/lib/python3.10/site-packages/transformers/models/auto/modeling_auto.py:1248: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn( ....
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.```

**Comment by jwes44** [comment]
I had the same problem then I read the readme and found this:
python -m spacy download en_core_web_sm

**Comment by TheGreatSimo** [comment]
I fixed it thank you bro
