### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by HamzaFarhan** [sai-prasanna/lmproof#5]
I ran:
pip install lmproof
python -m spacy download en
python -m spacy download en_core_web_sm

Then:
import lmproof
proof_reader = lmproof.load("en")

Then I got this error.

**Comment by sai-prasanna** [comment]
Sorry, I missed this notification. I will take a look.

Did you manage to fix it?

**Comment by HamzaFarhan** [comment]
No I wasn't able to fix it.

**Comment by sai-prasanna** [comment]
I was able to install and run the snippet.  I did only `python -m spacy download en`.
Can you repeat what you did without doing ` python -m spacy download en_core_web_sm`. 
It messes up the symlinks I guess.
