### ISSUE TITLE
How can we fine tune it on domain specific data?

### ISSUE THREAD

**Issue by Shivanandroy** [sai-prasanna/lmproof#6]

**Comment by sai-prasanna** [comment]
Hi, you would have to fine-tune the language model. And then it's a drop-in replacement.
It will work even if you don't use hugging face models. Just inherit the `SentenceScorer` abstract class.

https://github.com/sai-prasanna/lmproof/blob/4698af5ead46d785568624c78903b5735f7e3d30/lmproof/scorer.py#L16
